### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by yusuga** [mike-neko/NetworkInfo#2]
NetworkInfoのソースを利用したいと考えているのですが可能でしょうか？
利用可能でしたら、ライセンスを提示していただけると幸いです。

ちょうど求めていた内容なのと、Swiftらしいコードでとても綺麗ですね😄

**Comment by mike-neko** [comment]
わざわざありがとうございます。
ライセンスはMITですので、どうぞご自由に使ってやってください！

**Comment by yusuga** [comment]
ありがとうございます！
